version: '3.8'

x-node: &x-node
  build: .
  volumes:
    - ./config:/src/config
  environment:
    - DEPLOYMENT=docker-compose
    - USER=${USER}

services:
  database:
    image: bitnami/mariadb:10.5
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - database:/bitnami/mariadb
      # - ./corsaceInit.sql:/docker-entrypoint-initdb.d/corsaceInit.sql
    environment:
      - MARIADB_DATABASE=corsace
      - MARIADB_USER=corsace
      - MARIADB_PASSWORD=corsace
      - MARIADB_ROOT_PASSWORD=changeme
      # - BITNAMI_DEBUG=true
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 127.0.0.1:3380:80
    environment:
      - PMA_HOST=database
      - PMA_USER=corsace
      - PMA_PASSWORD=corsace
  centrifugo:
    image: centrifugo/centrifugo:v5.0.2
    network_mode: host
    volumes:
      - ./centrifugo-config.json:/centrifugo/config.json
    command: centrifugo -c config.json -p 8001
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  corsace:
    <<: *x-node
    ports:
      - 127.0.0.1:4000:4000
    command: "main"
  ayim:
    <<: *x-node
    ports:
      - 127.0.0.1:3000:3000
    command: "ayim"
  mca:
    <<: *x-node
    ports:
      - 127.0.0.1:8000:8000
    command: "mca"
  api:
    <<: *x-node
    ports:
      - 127.0.0.1:8080:8080
    command: "api"
  docs:
    <<: *x-node
    ports:
      - 127.0.0.1:10000:10000
  migrator:
    <<: *x-node
    command: "typeorm migration:run"

volumes:
  database:
